/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Administrador;
import Modelo.Conexion;
import Modelo.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Cristian Cruz
 */
public class FrmAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    Administrador administrador;
    Conexion conn;

    public FrmAdministrador(Administrador admin) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        conn = new Conexion();
        tfUsuario.setEditable(false);
        administrador = admin;
        tfUsuario.setText(admin.getNombre() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        jbAtras1 = new javax.swing.JButton();
        btnPreguntas = new javax.swing.JButton();
        btnJuegos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnPreguntas1 = new javax.swing.JButton();
        btnPeorJugador = new javax.swing.JButton();
        btnMejorJugador = new javax.swing.JButton();
        btnPartisPorce = new javax.swing.JButton();
        btnPorcentajeAciertos1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nickname");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        tfUsuario.setBackground(new java.awt.Color(0, 0, 0));
        tfUsuario.setFont(new java.awt.Font("Orator Std", 1, 36)); // NOI18N
        tfUsuario.setForeground(new java.awt.Color(153, 204, 255));
        tfUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2));
        tfUsuario.setCaretColor(new java.awt.Color(51, 255, 255));
        tfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 300, -1));

        jbAtras1.setBackground(new java.awt.Color(0, 51, 51));
        jbAtras1.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        jbAtras1.setForeground(new java.awt.Color(255, 255, 255));
        jbAtras1.setText("Atras");
        jbAtras1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbAtras1MouseReleased(evt);
            }
        });
        jbAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtras1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbAtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        btnPreguntas.setBackground(new java.awt.Color(0, 51, 51));
        btnPreguntas.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        btnPreguntas.setForeground(new java.awt.Color(204, 255, 255));
        btnPreguntas.setText("Administrar Preguntas");
        btnPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, 40));

        btnJuegos.setBackground(new java.awt.Color(0, 51, 51));
        btnJuegos.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        btnJuegos.setForeground(new java.awt.Color(204, 255, 255));
        btnJuegos.setText("Juegos Creados");
        btnJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegosActionPerformed(evt);
            }
        });
        getContentPane().add(btnJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 180, 40));

        btnUsuarios.setBackground(new java.awt.Color(0, 51, 51));
        btnUsuarios.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(204, 255, 255));
        btnUsuarios.setText("Administrar Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 240, 40));

        btnPreguntas1.setBackground(new java.awt.Color(0, 51, 51));
        btnPreguntas1.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        btnPreguntas1.setForeground(new java.awt.Color(204, 255, 255));
        btnPreguntas1.setText("Administrar Categorias");
        btnPreguntas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntas1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreguntas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, 40));

        btnPeorJugador.setBackground(new java.awt.Color(0, 51, 51));
        btnPeorJugador.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        btnPeorJugador.setForeground(new java.awt.Color(204, 255, 255));
        btnPeorJugador.setText("Datos del Jugador con el menor puntaje");
        btnPeorJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeorJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnPeorJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, -1, 40));

        btnMejorJugador.setBackground(new java.awt.Color(0, 51, 51));
        btnMejorJugador.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        btnMejorJugador.setForeground(new java.awt.Color(204, 255, 255));
        btnMejorJugador.setText("Datos del Jugador con el mayor puntaje");
        btnMejorJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMejorJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnMejorJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, 40));

        btnPartisPorce.setBackground(new java.awt.Color(0, 51, 51));
        btnPartisPorce.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        btnPartisPorce.setForeground(new java.awt.Color(204, 255, 255));
        btnPartisPorce.setText("participantes y sus porcentajes");
        btnPartisPorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartisPorceActionPerformed(evt);
            }
        });
        getContentPane().add(btnPartisPorce, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, 40));

        btnPorcentajeAciertos1.setBackground(new java.awt.Color(0, 51, 51));
        btnPorcentajeAciertos1.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        btnPorcentajeAciertos1.setForeground(new java.awt.Color(204, 255, 255));
        btnPorcentajeAciertos1.setText("Porcentaje de Aciertos de cada Pregunta");
        btnPorcentajeAciertos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajeAciertos1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPorcentajeAciertos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsuarioActionPerformed

    private void jbAtras1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAtras1MouseReleased


    }//GEN-LAST:event_jbAtras1MouseReleased

    private void jbAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtras1ActionPerformed
        new FrmInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbAtras1ActionPerformed

    private void btnPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntasActionPerformed
        new FrmRegistroPregunta(administrador).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPreguntasActionPerformed

    private void btnJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJuegosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed

        // TODO add your handling code here:
        new FrmGestionUsuarios(administrador).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnPreguntas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntas1ActionPerformed
        new FrmGestionCategorias(administrador).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPreguntas1ActionPerformed

    private void btnPeorJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeorJugadorActionPerformed
        try {

            conn.conectar();
            String dir = "C:\\GitHub\\Proyecto-Desarrollo\\ProyectoJuego\\src\\Reportes\\PeorEst.jrxml";
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null, conn.getConn());
            JasperViewer.viewReport(mostrarReporte);
            JasperExportManager.exportReportToPdfFile(mostrarReporte, "C:\\GitHub\\Proyecto-Desarrollo\\ProyectoJuego\\Pdfs\\PeorJugador.pdf");

        } catch (JRException ex) {
            Logger.getLogger(FrmAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        conn.desconectar();

    }//GEN-LAST:event_btnPeorJugadorActionPerformed

    private void btnMejorJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMejorJugadorActionPerformed
        try {

            conn.conectar();
            String dir = "C:\\GitHub\\Proyecto-Desarrollo\\ProyectoJuego\\src\\Reportes\\MejorEstu.jrxml";
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null, conn.getConn());
            JasperViewer.viewReport(mostrarReporte);
            JasperExportManager.exportReportToPdfFile(mostrarReporte, "C:\\GitHub\\Proyecto-Desarrollo\\ProyectoJuego\\Pdfs\\MejorJugador.pdf");

        } catch (JRException ex) {
            Logger.getLogger(FrmAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        conn.desconectar();
    }//GEN-LAST:event_btnMejorJugadorActionPerformed

    private void btnPartisPorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartisPorceActionPerformed
        try {

            conn.conectar();
            String dir = "C:\\GitHub\\Proyecto-Desarrollo\\ProyectoJuego\\src\\Reportes\\EstuPorc.jrxml";
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null, conn.getConn());
            JasperViewer.viewReport(mostrarReporte);
            JasperExportManager.exportReportToPdfFile(mostrarReporte, "C:\\GitHub\\Proyecto-Desarrollo\\ProyectoJuego\\Pdfs\\EstudiantesPuntajes.pdf");

        } catch (JRException ex) {
            Logger.getLogger(FrmAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        conn.desconectar();

    }//GEN-LAST:event_btnPartisPorceActionPerformed

    private void btnPorcentajeAciertos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajeAciertos1ActionPerformed
        try {

            conn.conectar();
            String dir = "C:\\GitHub\\Proyecto-Desarrollo\\ProyectoJuego\\src\\Reportes\\PregunPorcen.jrxml";
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null, conn.getConn());
            JasperViewer.viewReport(mostrarReporte);
            JasperExportManager.exportReportToPdfFile(mostrarReporte, "C:\\GitHub\\Proyecto-Desarrollo\\ProyectoJuego\\Pdfs\\PreguntasPorcentaje.pdf");

        } catch (JRException ex) {
            Logger.getLogger(FrmAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        conn.desconectar();
    }//GEN-LAST:event_btnPorcentajeAciertos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJuegos;
    private javax.swing.JButton btnMejorJugador;
    private javax.swing.JButton btnPartisPorce;
    private javax.swing.JButton btnPeorJugador;
    private javax.swing.JButton btnPorcentajeAciertos1;
    private javax.swing.JButton btnPreguntas;
    private javax.swing.JButton btnPreguntas1;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbAtras1;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
