/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlCategoria;
import javax.swing.JOptionPane;
import DAO.GenericoDAO;
import Modelo.Administrador;
import Modelo.Categoria;
import Modelo.Usuario;
import java.util.ArrayList;

/**
 *
 * @author Krull
 */
public class FrmGestionCategorias extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestionPreguntas
     */
    GenericoDAO DAOCategoria;
    CtlCategoria ctlCategoria;
    Administrador administrador;

    int categoriaID = 0;

    public FrmGestionCategorias(Administrador admin) {
        initComponents();
        administrador = admin;
        ctlCategoria = new CtlCategoria();
        DAOCategoria = new GenericoDAO();
        limpiar();
        listar();
        setLocationRelativeTo(this);
        setResizable(false);
    }

    FrmGestionCategorias(Usuario usuario) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        TblCategorias = new javax.swing.JTable();
        jbAtras2 = new javax.swing.JButton();
        BtnBuscarCategoria = new javax.swing.JButton();
        BtnRegistrarCategoria = new javax.swing.JButton();
        BtnModificarCategoria = new javax.swing.JButton();
        BtnEliminarCategoria = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreCategoria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblCategorias.setBackground(new java.awt.Color(0, 102, 153));
        TblCategorias.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        TblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        TblCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblCategoriasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TblCategorias);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 290, 250));

        jbAtras2.setBackground(new java.awt.Color(0, 51, 51));
        jbAtras2.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jbAtras2.setForeground(new java.awt.Color(255, 255, 255));
        jbAtras2.setText("Atras");
        jbAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtras2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        BtnBuscarCategoria.setBackground(new java.awt.Color(0, 51, 51));
        BtnBuscarCategoria.setFont(new java.awt.Font("Monotype Corsiva", 3, 28)); // NOI18N
        BtnBuscarCategoria.setForeground(new java.awt.Color(204, 255, 255));
        BtnBuscarCategoria.setText("Buscar Categoria");
        BtnBuscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 280, -1));

        BtnRegistrarCategoria.setBackground(new java.awt.Color(0, 51, 51));
        BtnRegistrarCategoria.setFont(new java.awt.Font("Monotype Corsiva", 3, 28)); // NOI18N
        BtnRegistrarCategoria.setForeground(new java.awt.Color(204, 255, 255));
        BtnRegistrarCategoria.setText("Registrar Categoria");
        BtnRegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 280, -1));

        BtnModificarCategoria.setBackground(new java.awt.Color(0, 51, 51));
        BtnModificarCategoria.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        BtnModificarCategoria.setForeground(new java.awt.Color(204, 255, 255));
        BtnModificarCategoria.setText("Modificar Categoria");
        BtnModificarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        BtnEliminarCategoria.setBackground(new java.awt.Color(0, 51, 51));
        BtnEliminarCategoria.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        BtnEliminarCategoria.setForeground(new java.awt.Color(204, 255, 255));
        BtnEliminarCategoria.setText("Eliminar Categoria");
        BtnEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 290, -1));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 80, 30));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lista de Categorias");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, 70));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 65)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Categorias");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 70));

        txtNombreCategoria.setBackground(new java.awt.Color(0, 0, 0));
        txtNombreCategoria.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        txtNombreCategoria.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        txtNombreCategoria.setCaretColor(new java.awt.Color(51, 255, 255));
        txtNombreCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreCategoriaMouseEntered(evt);
            }
        });
        txtNombreCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 220, -1));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TblCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblCategoriasMouseClicked
        // TODO add your handling code here:
        int pos = TblCategorias.getSelectedRow();

        if (pos >= 0) {
            Categoria categoria = ctlCategoria.CategoriaSeleccionada(pos);

            if (categoria != null) {
                txtNombreCategoria.setText(categoria.getNombre());
                categoriaID = categoria.getIdCategoria();
                jbAtras4.setEnabled(true);
                jbAtras5.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se encuentra la categoria seleccionada");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro");
        }
    }//GEN-LAST:event_TblCategoriasMouseClicked

    private void jbAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtras2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAtras2ActionPerformed

    private void BtnBuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarCategoriaActionPerformed

        try {
            String nickname = txtNombreCategoria.getText();
            String clave = tfClaves.getText();
            String nombres = tfNombres.getText();
            String apellidos = tfApellidos.getText();
            int codigo = Integer.parseInt(tfCodigo.getText());
            String correo = tfCorreo.getText();
            int semestre = Integer.parseInt(tfSemestre.getText());
            int idTipo = 2;

            if (controlador.SolicitudGuardar(nickname, clave, codigo, nombres, apellidos, correo, semestre, idTipo)) {

                JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }

        new FrmInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBuscarCategoriaActionPerformed

    private void BtnRegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarCategoriaActionPerformed

        try {
            String nickname = txtNombreCategoria.getText();
            String clave = tfClaves.getText();
            String nombres = tfNombres.getText();
            String apellidos = tfApellidos.getText();
            int codigo = Integer.parseInt(tfCodigo.getText());
            String correo = tfCorreo.getText();
            int semestre = Integer.parseInt(tfSemestre.getText());
            int idTipo = 2;

            if (controlador.SolicitudGuardar(nickname, clave, codigo, nombres, apellidos, correo, semestre, idTipo)) {

                JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }

        new FrmInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRegistrarCategoriaActionPerformed

    private void BtnModificarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarCategoriaActionPerformed

        try {
            String nickname = txtNombreCategoria.getText();
            String clave = tfClaves.getText();
            String nombres = tfNombres.getText();
            String apellidos = tfApellidos.getText();
            int codigo = Integer.parseInt(tfCodigo.getText());
            String correo = tfCorreo.getText();
            int semestre = Integer.parseInt(tfSemestre.getText());
            int idTipo = 2;

            if (controlador.SolicitudGuardar(nickname, clave, codigo, nombres, apellidos, correo, semestre, idTipo)) {

                JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }

        new FrmInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnModificarCategoriaActionPerformed

    private void BtnEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarCategoriaActionPerformed

        try {
            String nickname = txtNombreCategoria.getText();
            String clave = tfClaves.getText();
            String nombres = tfNombres.getText();
            String apellidos = tfApellidos.getText();
            int codigo = Integer.parseInt(tfCodigo.getText());
            String correo = tfCorreo.getText();
            int semestre = Integer.parseInt(tfSemestre.getText());
            int idTipo = 2;

            if (controlador.SolicitudGuardar(nickname, clave, codigo, nombres, apellidos, correo, semestre, idTipo)) {

                JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }

        new FrmInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnEliminarCategoriaActionPerformed

    private void txtNombreCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreCategoriaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCategoriaMouseEntered

    private void txtNombreCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCategoriaActionPerformed

    private void listar() {
        TblCategorias.setModel(ctlCategoria.SolicitudListar());
    }

    private void limpiar() {
        txtNombreCategoria.setText("");
        categoriaID = 0;
        jbAtras4.setEnabled(false);
        jbAtras5.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarCategoria;
    private javax.swing.JButton BtnEliminarCategoria;
    private javax.swing.JButton BtnModificarCategoria;
    private javax.swing.JButton BtnRegistrarCategoria;
    private javax.swing.JTable TblCategorias;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAtras2;
    private javax.swing.JTextField txtNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
