/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlCategoria;
import javax.swing.JOptionPane;
import DAO.GenericoDAO;
import Modelo.Administrador;
import Modelo.Categoria;
import java.util.ArrayList;

/**
 *
 * @author Krull
 */
public class FrmGestionPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestionPreguntas
     */
    GenericoDAO DAOCategoria;
    CtlCategoria ctlCategoria;
    Administrador administrador;

    int categoriaID = 0;

    public FrmGestionPreguntas(Administrador admin) {
        initComponents();
        administrador = admin;
        ctlCategoria = new CtlCategoria();
        DAOCategoria = new GenericoDAO();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnRegistrarPregunta = new javax.swing.JButton();
        BtnModificarPregunta = new javax.swing.JButton();
        BtnEliminarPregunta = new javax.swing.JButton();
        BtnBuscarPregunta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNombreCategoria = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblCategorias = new javax.swing.JTable();
        BtnRegistrarCategoria = new javax.swing.JButton();
        BtnModificarCategoria = new javax.swing.JButton();
        BtnBuscarCategoria = new javax.swing.JButton();
        BtnEliminarCategoria = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jbAtras = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 102, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdPregunta", "Descripcion", "idCategoria ", "idExamen"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 600, 150));

        BtnRegistrarPregunta.setBackground(new java.awt.Color(0, 51, 51));
        BtnRegistrarPregunta.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        BtnRegistrarPregunta.setForeground(new java.awt.Color(204, 255, 255));
        BtnRegistrarPregunta.setText("Registrar Pregunta");
        getContentPane().add(BtnRegistrarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        BtnModificarPregunta.setBackground(new java.awt.Color(0, 51, 51));
        BtnModificarPregunta.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        BtnModificarPregunta.setForeground(new java.awt.Color(204, 255, 255));
        BtnModificarPregunta.setText("Modificar Pregunta");
        BtnModificarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarPreguntaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        BtnEliminarPregunta.setBackground(new java.awt.Color(0, 51, 51));
        BtnEliminarPregunta.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        BtnEliminarPregunta.setForeground(new java.awt.Color(204, 255, 255));
        BtnEliminarPregunta.setText("Eliminar Pregunta");
        getContentPane().add(BtnEliminarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        BtnBuscarPregunta.setBackground(new java.awt.Color(0, 51, 51));
        BtnBuscarPregunta.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        BtnBuscarPregunta.setForeground(new java.awt.Color(204, 255, 255));
        BtnBuscarPregunta.setText("Buscar Pregunta");
        getContentPane().add(BtnBuscarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Preguntas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel2.setText("Lista de Categorias");

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel4.setText("Categorias");

        txtNombreCategoria.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(txtNombreCategoria);

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        TblCategorias.setBackground(new java.awt.Color(0, 102, 153));
        TblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ));
        TblCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblCategoriasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TblCategorias);

        BtnRegistrarCategoria.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        BtnRegistrarCategoria.setForeground(new java.awt.Color(204, 255, 255));
        BtnRegistrarCategoria.setText("Registrar Categoria");
        BtnRegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarCategoriaActionPerformed(evt);
            }
        });

        BtnModificarCategoria.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        BtnModificarCategoria.setForeground(new java.awt.Color(204, 255, 255));
        BtnModificarCategoria.setText("Modificar Categoria");
        BtnModificarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarCategoriaActionPerformed(evt);
            }
        });

        BtnBuscarCategoria.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        BtnBuscarCategoria.setForeground(new java.awt.Color(204, 255, 255));
        BtnBuscarCategoria.setText("Buscar Categoria");
        BtnBuscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarCategoriaActionPerformed(evt);
            }
        });

        BtnEliminarCategoria.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        BtnEliminarCategoria.setForeground(new java.awt.Color(204, 255, 255));
        BtnEliminarCategoria.setText("Eliminar Categoria");
        BtnEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnModificarCategoria)
                            .addComponent(BtnRegistrarCategoria)
                            .addComponent(BtnBuscarCategoria)
                            .addComponent(BtnEliminarCategoria))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRegistrarCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnBuscarCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnModificarCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnEliminarCategoria)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 500, 270));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Lista de Preguntas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jbAtras.setBackground(new java.awt.Color(0, 51, 51));
        jbAtras.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jbAtras.setForeground(new java.awt.Color(204, 255, 255));
        jbAtras.setText("Atras");
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jbAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jButton10.setBackground(new java.awt.Color(0, 51, 51));
        jButton10.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 255, 255));
        jButton10.setText("Mostrar Soluciones");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarCategoriaActionPerformed
        // TODO add your handling code here:

        try {
            String nombre = txtNombreCategoria.getText();

            if (ctlCategoria.SolicitudGuardar(nombre)) {
                JOptionPane.showMessageDialog(this, "Guardado exitosamente");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }
        listar();


    }//GEN-LAST:event_BtnRegistrarCategoriaActionPerformed

    private void BtnBuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarCategoriaActionPerformed
        // TODO add your handling code here
        try {

            String nombre = txtNombreCategoria.getText();
            ArrayList<Categoria> categoria = ctlCategoria.SolicitudBuscar(nombre);

            if (categoria.size() > 0) {
                JOptionPane.showMessageDialog(null, "La categoria ha sido encontrada");
                for (int i = 0; i < categoria.size(); i++) {
                    TblCategorias.setModel(ctlCategoria.ListarBusqueda(categoria));
                }
            } else {
                JOptionPane.showMessageDialog(null, "La categoria no ha sido encontrada");
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Error al cargar los datos");
            limpiar();
        }

    }//GEN-LAST:event_BtnBuscarCategoriaActionPerformed

    private void BtnModificarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarCategoriaActionPerformed
        // TODO add your handling code here:

        try {
            String nombre = txtNombreCategoria.getText();

            if (ctlCategoria.SolicitudModificar(categoriaID, nombre)) {
                JOptionPane.showMessageDialog(this, "Modificado exitosamente");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }
        listar();

    }//GEN-LAST:event_BtnModificarCategoriaActionPerformed

    private void BtnEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarCategoriaActionPerformed
        // TODO add your handling code here:

        categoriaID = Integer.parseInt(JOptionPane.showInputDialog("Por favor ingrese el ID de la categoria:"));
        if (ctlCategoria.SolicitudEliminar(categoriaID)) {
            JOptionPane.showMessageDialog(this, "Eliminado exitosamente");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar");
        }
        listar();

    }//GEN-LAST:event_BtnEliminarCategoriaActionPerformed

    private void BtnModificarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarPreguntaActionPerformed

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAtrasActionPerformed

    private void TblCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblCategoriasMouseClicked
        // TODO add your handling code here:
        int pos = TblCategorias.getSelectedRow();

        if (pos >= 0) {
            Categoria categoria = ctlCategoria.CategoriaSeleccionada(pos);

            if (categoria != null) {
                txtNombreCategoria.setText(categoria.getNombre());
                categoriaID = categoria.getIdCategoria();
                BtnEliminarCategoria.setEnabled(true);
                BtnModificarCategoria.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se encuentra la categoria seleccionada");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro");
        }
    }//GEN-LAST:event_TblCategoriasMouseClicked

    private void listar() {
        TblCategorias.setModel(ctlCategoria.SolicitudListar());
    }

    private void limpiar() {
        txtNombreCategoria.setText("");
        categoriaID = 0;
        BtnEliminarCategoria.setEnabled(false);
        BtnModificarCategoria.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarCategoria;
    private javax.swing.JButton BtnBuscarPregunta;
    private javax.swing.JButton BtnEliminarCategoria;
    private javax.swing.JButton BtnEliminarPregunta;
    private javax.swing.JButton BtnModificarCategoria;
    private javax.swing.JButton BtnModificarPregunta;
    private javax.swing.JButton BtnRegistrarCategoria;
    private javax.swing.JButton BtnRegistrarPregunta;
    private javax.swing.JTable TblCategorias;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAtras;
    private javax.swing.JTextPane txtNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
