/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Cristian Cruz
 */
public class FrmInicioJuego extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicioJuego
     */
    public FrmInicioJuego() {
        initComponents();
        
        setLocationRelativeTo(this);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbPregunta = new javax.swing.JLabel();
        Chb1 = new javax.swing.JCheckBox();
        Chb2 = new javax.swing.JCheckBox();
        Chb3 = new javax.swing.JCheckBox();
        Chb4 = new javax.swing.JCheckBox();
        BtnSiguiente = new javax.swing.JButton();
        LbCategoria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbPregunta.setBackground(new java.awt.Color(0, 0, 0));
        LbPregunta.setFont(new java.awt.Font("Wide Latin", 3, 18)); // NOI18N
        LbPregunta.setForeground(new java.awt.Color(255, 255, 255));
        LbPregunta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        LbPregunta.setOpaque(true);
        getContentPane().add(LbPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 400, 90));

        Chb1.setBackground(new java.awt.Color(0, 0, 0));
        Chb1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Chb1.setForeground(new java.awt.Color(255, 255, 255));
        Chb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chb1ActionPerformed(evt);
            }
        });
        getContentPane().add(Chb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 60, 30));

        Chb2.setBackground(new java.awt.Color(0, 0, 0));
        Chb2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Chb2.setForeground(new java.awt.Color(255, 255, 255));
        Chb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chb2ActionPerformed(evt);
            }
        });
        getContentPane().add(Chb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 60, 30));

        Chb3.setBackground(new java.awt.Color(0, 0, 0));
        Chb3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Chb3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Chb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 60, 30));

        Chb4.setBackground(new java.awt.Color(0, 0, 0));
        Chb4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Chb4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Chb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 60, 30));

        BtnSiguiente.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        BtnSiguiente.setForeground(new java.awt.Color(255, 0, 0));
        BtnSiguiente.setText("SIGUIENTE");
        getContentPane().add(BtnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, 32));

        LbCategoria.setBackground(new java.awt.Color(0, 0, 0));
        LbCategoria.setText("jLabel2");
        LbCategoria.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        LbCategoria.setOpaque(true);
        getContentPane().add(LbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/light-1443836_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Chb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chb1ActionPerformed

    private void Chb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Chb2ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JCheckBox Chb1;
    private javax.swing.JCheckBox Chb2;
    private javax.swing.JCheckBox Chb3;
    private javax.swing.JCheckBox Chb4;
    private javax.swing.JLabel LbCategoria;
    private javax.swing.JLabel LbPregunta;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
