/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtlUsuario;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian Cruz
 */
public class FrmRegistrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistro
     */
    CtlUsuario controlador;

    public FrmRegistrarUsuario() {
        setLocationRelativeTo(this);
        initComponents();

        setResizable(false);
        controlador = new CtlUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAtras = new javax.swing.JButton();
        tfSemestre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNombres = new javax.swing.JTextField();
        tfClaves = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfNickname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        jbRegistrarUsuario1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbAtras.setBackground(new java.awt.Color(0, 51, 51));
        jbAtras.setFont(new java.awt.Font("Monotype Corsiva", 3, 24)); // NOI18N
        jbAtras.setForeground(new java.awt.Color(255, 255, 255));
        jbAtras.setText("Atras");
        jbAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbAtrasMouseReleased(evt);
            }
        });
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jbAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        tfSemestre.setBackground(new java.awt.Color(0, 0, 0));
        tfSemestre.setFont(new java.awt.Font("Orator Std", 1, 24)); // NOI18N
        tfSemestre.setForeground(new java.awt.Color(255, 255, 255));
        tfSemestre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSemestre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        tfSemestre.setCaretColor(new java.awt.Color(51, 255, 255));
        tfSemestre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfSemestreMouseEntered(evt);
            }
        });
        tfSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSemestreActionPerformed(evt);
            }
        });
        tfSemestre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSemestreKeyTyped(evt);
            }
        });
        getContentPane().add(tfSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 200, -1));

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Semestre:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, 20));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, 20));

        tfCodigo.setBackground(new java.awt.Color(0, 0, 0));
        tfCodigo.setFont(new java.awt.Font("Orator Std", 1, 24)); // NOI18N
        tfCodigo.setForeground(new java.awt.Color(255, 255, 255));
        tfCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        tfCodigo.setCaretColor(new java.awt.Color(51, 255, 255));
        tfCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCodigoMouseEntered(evt);
            }
        });
        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });
        tfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 200, -1));

        tfApellidos.setBackground(new java.awt.Color(0, 0, 0));
        tfApellidos.setFont(new java.awt.Font("Orator Std", 1, 24)); // NOI18N
        tfApellidos.setForeground(new java.awt.Color(255, 255, 255));
        tfApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        tfApellidos.setCaretColor(new java.awt.Color(51, 255, 255));
        tfApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfApellidosMouseEntered(evt);
            }
        });
        tfApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidosActionPerformed(evt);
            }
        });
        tfApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfApellidosKeyTyped(evt);
            }
        });
        getContentPane().add(tfApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 200, -1));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Apellidos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, 20));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Nombres:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, 20));

        tfNombres.setBackground(new java.awt.Color(0, 0, 0));
        tfNombres.setFont(new java.awt.Font("Orator Std", 1, 24)); // NOI18N
        tfNombres.setForeground(new java.awt.Color(255, 255, 255));
        tfNombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        tfNombres.setCaretColor(new java.awt.Color(51, 255, 255));
        tfNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNombresMouseEntered(evt);
            }
        });
        tfNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombresActionPerformed(evt);
            }
        });
        tfNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombresKeyTyped(evt);
            }
        });
        getContentPane().add(tfNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 200, -1));

        tfClaves.setBackground(new java.awt.Color(0, 0, 0));
        tfClaves.setFont(new java.awt.Font("Orator Std", 1, 24)); // NOI18N
        tfClaves.setForeground(new java.awt.Color(255, 255, 255));
        tfClaves.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfClaves.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        tfClaves.setCaretColor(new java.awt.Color(51, 255, 255));
        tfClaves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfClavesMouseEntered(evt);
            }
        });
        tfClaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClavesActionPerformed(evt);
            }
        });
        getContentPane().add(tfClaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 200, -1));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Clave:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, 20));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("NickName:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, 20));

        tfNickname.setBackground(new java.awt.Color(0, 0, 0));
        tfNickname.setFont(new java.awt.Font("Orator Std", 1, 24)); // NOI18N
        tfNickname.setForeground(new java.awt.Color(255, 255, 255));
        tfNickname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNickname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        tfNickname.setCaretColor(new java.awt.Color(51, 255, 255));
        tfNickname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNicknameMouseEntered(evt);
            }
        });
        tfNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNicknameActionPerformed(evt);
            }
        });
        getContentPane().add(tfNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 200, -1));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 204, 255));
        jLabel10.setText("Registro");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 190, -1));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 204, 255));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 290, -1));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Correo Electronico:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, 20));

        tfCorreo.setBackground(new java.awt.Color(0, 0, 0));
        tfCorreo.setFont(new java.awt.Font("Orator Std", 1, 24)); // NOI18N
        tfCorreo.setForeground(new java.awt.Color(255, 255, 255));
        tfCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        tfCorreo.setCaretColor(new java.awt.Color(51, 255, 255));
        tfCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCorreoMouseEntered(evt);
            }
        });
        tfCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(tfCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 200, -1));

        jbRegistrarUsuario1.setBackground(new java.awt.Color(0, 51, 51));
        jbRegistrarUsuario1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jbRegistrarUsuario1.setForeground(new java.awt.Color(204, 255, 255));
        jbRegistrarUsuario1.setText("Registrar");
        jbRegistrarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarUsuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbRegistrarUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtrasActionPerformed
 new FrmInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbAtrasActionPerformed

    private void tfSemestreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSemestreMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSemestreMouseEntered

    private void tfSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSemestreActionPerformed

    private void tfCodigoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCodigoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoMouseEntered

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void tfApellidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfApellidosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidosMouseEntered

    private void tfApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidosActionPerformed

    private void tfNombresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNombresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombresMouseEntered

    private void tfNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombresActionPerformed

    private void tfClavesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfClavesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClavesMouseEntered

    private void tfClavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClavesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClavesActionPerformed

    private void tfNicknameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNicknameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNicknameMouseEntered

    private void tfNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNicknameActionPerformed

    private void tfCorreoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCorreoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCorreoMouseEntered

    private void tfCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCorreoActionPerformed

    private void jbRegistrarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarUsuario1ActionPerformed

        try {
            String nickname = tfNickname.getText();
            String clave = tfClaves.getText();
            String nombres = tfNombres.getText();
            String apellidos = tfApellidos.getText();
            int codigo = Integer.parseInt(tfCodigo.getText());
            String correo = tfCorreo.getText();
            int semestre = Integer.parseInt(tfSemestre.getText());
            int idTipo = 2;

            if (controlador.SolicitudGuardar(nickname, clave, codigo, nombres, apellidos, correo, semestre, idTipo)) {

                JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }

        new FrmInicio().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbRegistrarUsuario1ActionPerformed

    private void jbAtrasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAtrasMouseReleased
        new FrmInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbAtrasMouseReleased

    private void tfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyTyped
        // TODO add your handling code here:

        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
            evt.consume();
        }

    }//GEN-LAST:event_tfCodigoKeyTyped

    private void tfSemestreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSemestreKeyTyped
        // TODO add your handling code here:
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_tfSemestreKeyTyped

    private void tfNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombresKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_tfNombresKeyTyped

    private void tfApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidosKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_tfApellidosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbAtras;
    private javax.swing.JButton jbRegistrarUsuario1;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfClaves;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfNickname;
    private javax.swing.JTextField tfNombres;
    private javax.swing.JTextField tfSemestre;
    // End of variables declaration//GEN-END:variables
}
